apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::533677770464:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::533677770464:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-A8Q8RWR6BNJ5
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-27T14:28:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "880"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 26c8528e-2c0a-11ea-9c91-0a722403f242
